### ISSUE TITLE
Cannot compile against Varnish 5.1.2

### ISSUE THREAD

**Issue by lukaszlach** [gquintard/libvmod-accept#1]
`master` branch does not compile against Varnish 5.

```
checking for Varnish... 5.1.2
configure: error: Varnish version below 5.1 is required.
```

There is also no specific branch nor tag to work with this version, only `master` is available. Does the vmod support Varnish 5 at all?

**Comment by gquintard** [comment]
Fixed with e043d4c
Thanks @lukaszlach , the configure test was a tidbit too strict.
