### ISSUE TITLE
case sensitive

### ISSUE THREAD

**Issue by dbu** [gquintard/libvmod-accept#4]
we just noticed that the accept rules we set for languages seem to be case sensitive. our backend is not case sensitive, so introducing this module broke some clients that sent an UPPERCASE language. we changed to `accept_lang_rules.filter(std.tolower(req.http.Accept-Language))` to work around the issue, but i wanted to ask if this is designed like this on purpose or not. if its on purpose, i suggest to update the readme to mention that and maybe change the lang_rules example to use std.tolower.

**Comment by gquintard** [comment]
Hello @dbu,

I have no strong opinions about this. I couldn't see in the spec that tests should be case-insensitive, but if you have any pointers, I'll gladly look at them.

In the meantime, your work around does the trick, and I'll gladly review any PR you send this way.

Cheers,

**Comment by dbu** [comment]
i did some googling and stumbled upon https://tools.ietf.org/html/bcp47#section-2.1.1 which states that language tags are considered case insensitive. https://tools.ietf.org/html/rfc2616#page-104 unfortunately does not mention this.

**Comment by dbu** [comment]
so bcp seems to be "best practices" rather than binding standards. seems to me to indicate the module should treat languages case insensitive.

**Comment by gquintard** [comment]
@dbu : fixed in 38a0444, let me know if you need more.

Thanks for the issue and for the research!

**Comment by dbu** [comment]
awesome, thanks!
